/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model.glb -T --shadows 
Files: model.glb [47.21MB] > model-transformed.glb [3.02MB] (94%)
Author: KrStolorz (Krzysztof Stolorz) (https://sketchfab.com/KrStolorz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/1974-volkswagen-golf-mk1-lp-2193b76ebc66474a8dac01242014c911
Title: 1974 Volkswagen Golf Mk1 (LP)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.Paint} position={[0.735, 0.62, 0.716]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Body} position={[0.735, 0.62, 0.716]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Glass} position={[0.649, 1.095, 0.133]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.Wheel} position={[0.694, 0.291, -1.2]} rotation={[2.869, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.Interior} position={[-0.553, 0.419, 0.209]} rotation={[0.114, 0.312, -0.702]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_71.geometry} material={materials.Lights} />
      <mesh castShadow receiveShadow geometry={nodes.Object_75.geometry} material={materials.Plate} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
